### ISSUE TITLE
Openexr

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [alexrives/homebrew-torch#1]
Hi !
 I would like to load exr files as tensor. Is it doable it with your package ?
Thank you for your work :+1:

**Comment by alexrives** [comment]
Thanks! These are just linuxbrew formulas to install dependencies locally for torch. It's a few years out of date now and the current version of torch has a self contained install. You could check out pytorch (http://pytorch.org), especially the torch vision package, to see if that can help. I'll probably take this repo down in a day or two.
